### ISSUE TITLE
KeyError: 'mem_fragmentation_ratio'

### ISSUE THREAD

**Issue by sylarjiang** [iambocai/falcon-monit-scripts#10]
env:centos7+python2.7

`[root@openfalcon redis]# python redis-monitor.py 
Traceback (most recent call last):

  File "redis-monitor.py", line 116, in <module>
    main()
  File "redis-monitor.py", line 75, in main
    value = float(stats[key])
KeyError: 'mem_fragmentation_ratio'`

help!

**Comment by sylarjiang** [comment]
我把那个判断语句注释掉又出现

`[root@openfalcon redis]# python redis-monitor.py 

Traceback (most recent call last):
  File "redis-monitor.py", line 116, in <module>
    main()
  File "redis-monitor.py", line 71, in main
    value = float(stats['keyspace_hits'])/(int(stats['keyspace_hits']) + int(stats['keyspace_misses']))
KeyError: 'keyspace_hits'
`

**Comment by iambocai** [comment]
@sylarjiang  可能是你redis版本过低，或者是一个全新的redis实例，我脚本改了下，遇到没有的key直接跳过了，你试试看是否ok了
